// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eogzmfpioypmrcbjnvtd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvZ3ptZnBpb3lwbXJjYmpudnRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NzQ2OTMsImV4cCI6MjA2ODQ1MDY5M30.4V5soD786kQMSs26RFCPezT9tpf5BGmz8JJD_RECjXU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});